# LogConfig
ARCH_FILE_NAME = 'Arch.zip'
LOG_FILES_DIRECTORY = 'Config/LogFiles'
LOG_FILE_NAME = "UMNWWCHS.log"

# Model Storage
RF___SAV = "RF_1.sav"
RF_TYPE_DIRECTORY = "/Rf"

SVN___SAV = "SVN_1.sav"
SVN_TYPE_DIRECTORY = "/Svn"

KNN___SAV = "KNN_1.sav"
KNN_TYPE_DIRECTORY = "/Knn"

MODULE_DIRECTORY_PATH = 'ComparativeSupervisedLearning/PredictionManagement/'

SAV_DIR = "/Sav/"

KNN_FULL_PATH_SAV = MODULE_DIRECTORY_PATH + KNN_TYPE_DIRECTORY + SAV_DIR + KNN___SAV
SVN_FULL_PATH_SAV = MODULE_DIRECTORY_PATH + SVN_TYPE_DIRECTORY + SAV_DIR + SVN___SAV
RF_FULL_PATH_SAV = MODULE_DIRECTORY_PATH + RF_TYPE_DIRECTORY + SAV_DIR + RF___SAV

MODEL_TYPE_KNN = "Knn"
MODEL_TYPE_SVN = "Svn"
MODEL_TYPE_RF = "Rf"

MODELS = [MODEL_TYPE_KNN, MODEL_TYPE_SVN, MODEL_TYPE_RF]
